### ISSUE TITLE
Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by yoanmarchal** [drozhzhin-n-e/vue-pinch-zoom#14]
In mounted component , if component is set as disabled="true",
VueComponent.PinchZoom.beforeDestroy cant destroy himself
`Error in beforeDestroy hook: "TypeError: Cannot read property 'destroy' of undefined"`

**Comment by juventus18** [comment]
I am also getting similar errors, but I am not disabling the component using `disabled="true"`

```
TypeError: Cannot read properties of null (reading 'tagName')
    at new IvyPinch (app.js:77136:57)
    at VueComponent.PinchZoom.init (app.js:77701:21)
    at VueComponent.PinchZoom.mounted (app.js:77651:10)
    at invokeWithErrorHandling (app.js:18845:57)
    at callHook (app.js:21205:7)
    at Object.insert (app.js:20128:7)
    at invokeInsertHook (app.js:23328:28)
    at VueComponent.patch [as __patch__] (app.js:23547:5)
    at VueComponent.Vue._update (app.js:20934:19)
    at VueComponent.updateComponent (app.js:21046:10)
  ```
  and 
  
  ```
  TypeError: Cannot read properties of undefined (reading 'destroy')
    at VueComponent.PinchZoom.beforeDestroy (app.js:77655:19)
    at invokeWithErrorHandling (app.js:18845:57)
    at callHook (app.js:21205:7)
    at VueComponent.Vue.$destroy (app.js:20964:5)
    at destroy (app.js:20148:27)
    at invokeDestroyHook (app.js:23096:59)
    at invokeDestroyHook (app.js:23101:9)
    at invokeDestroyHook (app.js:23101:9)
    at invokeDestroyHook (app.js:23101:9)
    at invokeDestroyHook (app.js:23101:9)
  ```
